server:
  port: 8080

zx:
  message-push:
    mail:
      account:
        - host: "smtp.qq.com"
          port: 465
          ssl-enable: true
          authEnable: true
          from: "747945307@qq.com"
          flag: "mail-1001"
          auth:
            username: "747945307@qq.com"
            password: "1111111111111111"
          socket:
            timeout: 60000
            connection-timeout: 30000
          start-tls-enabled: true
          start-tls-required: true
          pop-before-smtp: false
          pop-account:
            pop-host: "pop3.example.com"
            pop-username: "user@example.com"
            pop-password: "password"
          debug: false
